services:
  - type: web
    name: ig-repost
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        sync: false
      - key: IG_USERNAME
        sync: false
      - key: IG_PASSWORD
        sync: false
      - key: IG_TOTP_SEED
        sync: false
      - key: IG_SESSIONID
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: CF_ACCOUNT_ID
        sync: false
      - key: CF_API_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
        sync: false
